version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  cerver:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/app/
    environment:
      - CURR_ENV=development
    ports:
      - '7001:7001'
    depends_on:
      - mongo